### ISSUE TITLE
There might be an error in the poker gym env.

### ISSUE THREAD

**Issue by williamyuanv0** [fschlatt/clubs_gym#5]
Hi, fschlatt,
      when I run the _example.py_, I meet an error as follows:

Traceback (most recent call last):
  File "E:\code\poker\clubs_gym-main\clubs_gym-main\example.py", line 5, in <module>
    env = gym.make("KuhnTwoPlayer-v0")
  File "D:\anaconda23\envs\gympoker\lib\site-packages\gym\envs\registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "D:\anaconda23\envs\gympoker\lib\site-packages\gym\wrappers\env_checker.py", line 27, in __init__
    check_observation_space(env.observation_space)
  File "D:\anaconda23\envs\gympoker\lib\site-packages\gym\utils\passive_env_checker.py", line 109, in check_space
    check_space(subspace, space_type, check_box_space_fn)
  File "D:\anaconda23\envs\gympoker\lib\site-packages\gym\utils\passive_env_checker.py", line 101, in check_space
    ), f"An empty Tuple {space_type} space is not allowed."
AssertionError: An empty Tuple observation space is not allowed.

And my conda env is shown as follows:
Package            Version
------------------ ---------
certifi            2022.12.7
cloudpickle        2.2.1
clubs              0.1.4
clubs-gym          0.1.4
gym                0.26.2
gym-notices        0.0.8
importlib-metadata 6.0.0
numpy              1.21.6
pip                22.3.1
setuptools         65.6.3
typing_extensions  4.5.0
wheel              0.38.4
wincertstore       0.2
zipp               3.15.0

**Comment by williamyuanv0** [comment]
It works with gym==0.18.0
